name: files
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  image_picker: ^1.1.1
  image_cropper: ^6.0.0
  image_editor_plus: ^1.0.5
  flutter_image_filters: ^0.0.18
  http: ^1.2.1
  meta: ^1.11.0
  bloc: ^8.1.4
  permission_handler: ^11.3.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
